function [X,Y,Z] = rotation3(X,Y,Z,x,y,z)
% define rotation matrix
Rx = [...
        1, 0, 0;...
        0, cosd(x), -sind(x);...
        0, sind(x), cosd(x)];
Ry = [...
        cosd(y), 0, sind(y);...
        0, 1, 0;...
        -sind(y), 0, cosd(y)];
Rz = [...
        cosd(z), -sind(z), 0;...
        sind(z), cosd(z), 0;...
        0, 0, 1];
    
R = Rx'*Ry'*Rz';

% rotate vertices

for i=1:length(X)
    pts = [X(i), Y(i), Z(i)]*R;
    
    X(i) = pts(:,1);
    Y(i) = pts(:,2);
    Z(i) = pts(:,3);
end
end